[package]
name = "chibicc_in_Rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "step1"
path = "examples/step1.rs"

[[bin]]
name = "test"
path = "examples/test.rs"